name: Continous Deployment [Staging]
on:
  push:
    branches:
      - staging
      - dev
jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROPRLY_DEV_SERVER_HOST }}
          username: ${{ secrets.PROPRLY_DEV_SERVER_USER }}
          key: ${{ secrets.PROPRLY_DEV_SERVER_KEY }}
          port: ${{ secrets.PROPRLY_DEV_SERVER_PORT }}
          script_stop: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd proprly-admin-staging
            git fetch
            git reset --hard origin/staging
            git pull origin staging
            npm install
            npm run build
            pm2 restart proprly-admin-staging
