name: Continous Deployment [Staging]
on:
  push:
    branches:
      - staging

permissions:
  contents: read
  deployments: write

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Deployment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/deployments \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d '{
              "ref": "${{ github.sha }}",
              "environment": "staging",
              "required_contexts": [],
              "auto_merge": false,
              "description": "Deployment triggered from GitHub Actions"
            }' > deployment.json

      - name: Get Deployment ID
        run: |
          cat deployment.json
          echo "DEPLOYMENT_ID=$(jq -r .id deployment.json)" >> $GITHUB_ENV

      - name: executing remote ssh commands on remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PROPRLY_DEV_SERVER_HOST }}
          username: ${{ secrets.PROPRLY_DEV_SERVER_USER }}
          key: ${{ secrets.PROPRLY_DEV_SERVER_KEY }}
          port: ${{ secrets.PROPRLY_DEV_SERVER_PORT }}
          script_stop: true
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            cd proprly-admin-staging
            git fetch
            git reset --hard origin/staging
            git pull origin staging
            npm install -g yarn
            yarn install
            yarn build
            pm2 restart proprly-admin-staging

      - name: Update Deployment Status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/deployments/${{ env.DEPLOYMENT_ID }}/statuses \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            -d '{
              "state": "success",
              "environment": "staging",
              "description": "Deployed to staging server"
            }'
